// Stub file for vitest import resolution.
// The real file is generated by `wails dev` and is gitignored.
// This stub prevents build-time import failures in tests.

/**
 * @returns {Promise<Array<{name: string, status: string, message: string}>>}
 */
export function GetAdapterStatus() {
    return window["go"]["services/capture"]["CaptureManager"]["GetAdapterStatus"]();
}
