// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FilterCommand(arg1) {
  return window['go']['services']['LLMService']['FilterCommand'](arg1);
}

export function RebuildProvider() {
  return window['go']['services']['LLMService']['RebuildProvider']();
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['services']['LLMService']['SendMessage'](arg1, arg2, arg3);
}

export function SetAPIKeyEnclave(arg1, arg2) {
  return window['go']['services']['LLMService']['SetAPIKeyEnclave'](arg1, arg2);
}

export function SetAuditLogger(arg1, arg2) {
  return window['go']['services']['LLMService']['SetAuditLogger'](arg1, arg2);
}

export function SetCaptureManager(arg1) {
  return window['go']['services']['LLMService']['SetCaptureManager'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['LLMService']['Startup'](arg1);
}
