// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {memguard} from '../models';
import {audit} from '../models';
import {services} from '../models';
import {context} from '../models';

export function FilterCommand(arg1:string):Promise<string>;

export function RebuildProvider():Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetAPIKeyEnclave(arg1:string,arg2:memguard.Enclave):Promise<void>;

export function SetAuditLogger(arg1:audit.AuditLogger,arg2:string):Promise<void>;

export function SetCaptureManager(arg1:services.filterPipelineRebuilder):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
