// Auto-generated stub for LLMService Wails bindings.
// The real file is generated by `wails dev` at runtime and excluded by .gitignore.
// This stub is committed so that vitest can resolve the import path in tests.

export function SendMessage() { return Promise.resolve(); }
export function FilterCommand() { return Promise.resolve(""); }
export function Startup() { return Promise.resolve(); }
