// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenNewTerminal(arg1) {
  return window['go']['services']['PTYService']['OpenNewTerminal'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['services']['PTYService']['ResizeTerminal'](arg1, arg2, arg3);
}

export function WriteInput(arg1, arg2) {
  return window['go']['services']['PTYService']['WriteInput'](arg1, arg2);
}
