// Auto-generated stub for SettingsService Wails bindings.
// The real file is generated by `wails dev` at runtime and excluded by .gitignore.
// This stub is committed so that vitest can resolve the import path in tests.

export function GetSettings() { return Promise.resolve({}); }
export function SaveSettings() { return Promise.resolve(); }
export function GetAPIKeyStatus() { return Promise.resolve(""); }
export function SaveAPIKey() { return Promise.resolve(); }
export function TestConnection() { return Promise.resolve("Connected"); }
export function SetModel() { return Promise.resolve(""); }
export function SetContextLines() { return Promise.resolve(""); }
export function ForceRefresh() { return Promise.resolve(""); }
export function ExportChat() { return Promise.resolve(""); }
export function RenameTab() { return Promise.resolve(""); }
