// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {config} from '../models';
import {context} from '../models';

export function ExportChat(arg1:string,arg2:string,arg3:Array<services.ExportMessage>):Promise<string>;

export function ForceRefresh():Promise<string>;

export function GetAPIKeyStatus(arg1:string):Promise<string>;

export function GetSettings():Promise<config.AppConfig>;

export function RenameTab(arg1:string,arg2:string):Promise<string>;

export function SaveAPIKey(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:config.AppConfig):Promise<void>;

export function SetCaptureManager(arg1:services.captureManagerForceCapture):Promise<void>;

export function SetContextLines(arg1:number):Promise<string>;

export function SetLLMService(arg1:services.LLMService):Promise<void>;

export function SetModel(arg1:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function TestConnection(arg1:string,arg2:string):Promise<string>;
