// Stub file for vitest import resolution.
// The real file is generated by `wails dev` and is gitignored.
// This stub prevents build-time import failures in tests.

/**
 * @returns {Promise<Object>}
 */
export function GetSettings() {
  return window["go"]["services"]["SettingsService"]["GetSettings"]();
}

/**
 * @param {Object} cfg
 * @returns {Promise<void>}
 */
export function SaveSettings(cfg) {
  return window["go"]["services"]["SettingsService"]["SaveSettings"](cfg);
}

/**
 * @param {string} provider
 * @returns {Promise<string>}
 */
export function GetAPIKeyStatus(provider) {
  return window["go"]["services"]["SettingsService"]["GetAPIKeyStatus"](provider);
}

/**
 * @param {string} provider
 * @param {string} key
 * @returns {Promise<void>}
 */
export function SaveAPIKey(provider, key) {
  return window["go"]["services"]["SettingsService"]["SaveAPIKey"](provider, key);
}

/**
 * @returns {Promise<string>}
 */
export function TestConnection() {
  return window["go"]["services"]["SettingsService"]["TestConnection"]();
}

/**
 * @param {string} model
 * @returns {Promise<string>}
 */
export function SetModel(model) {
  return window["go"]["services"]["SettingsService"]["SetModel"](model);
}
