// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportChat(arg1, arg2, arg3) {
  return window['go']['services']['SettingsService']['ExportChat'](arg1, arg2, arg3);
}

export function ForceRefresh() {
  return window['go']['services']['SettingsService']['ForceRefresh']();
}

export function GetAPIKeyStatus(arg1) {
  return window['go']['services']['SettingsService']['GetAPIKeyStatus'](arg1);
}

export function GetSettings() {
  return window['go']['services']['SettingsService']['GetSettings']();
}

export function RenameTab(arg1, arg2) {
  return window['go']['services']['SettingsService']['RenameTab'](arg1, arg2);
}

export function SaveAPIKey(arg1, arg2) {
  return window['go']['services']['SettingsService']['SaveAPIKey'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['services']['SettingsService']['SaveSettings'](arg1);
}

export function SetCaptureManager(arg1) {
  return window['go']['services']['SettingsService']['SetCaptureManager'](arg1);
}

export function SetContextLines(arg1) {
  return window['go']['services']['SettingsService']['SetContextLines'](arg1);
}

export function SetLLMService(arg1) {
  return window['go']['services']['SettingsService']['SetLLMService'](arg1);
}

export function SetModel(arg1) {
  return window['go']['services']['SettingsService']['SetModel'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['SettingsService']['Startup'](arg1);
}

export function TestConnection(arg1, arg2) {
  return window['go']['services']['SettingsService']['TestConnection'](arg1, arg2);
}
