// Type declarations for Wails runtime stub.
// The actual runtime is generated by `wails dev` / `wails build`.
// This stub provides minimal type coverage for testing.

export declare function EventsOn(eventName: string, callback: (...args: unknown[]) => void): () => void;
export declare function EventsOff(eventName: string): void;
export declare function EventsEmit(eventName: string, ...data: unknown[]): void;
