// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForceCapture() {
  return window['go']['capture']['CaptureManager']['ForceCapture']();
}

export function GetAdapterStatus() {
  return window['go']['capture']['CaptureManager']['GetAdapterStatus']();
}

export function RebuildFilterPipeline() {
  return window['go']['capture']['CaptureManager']['RebuildFilterPipeline']();
}

export function Startup(arg1) {
  return window['go']['capture']['CaptureManager']['Startup'](arg1);
}
