// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {capture} from '../models';
import {context} from '../models';

export function ForceCapture():Promise<void>;

export function GetAdapterStatus():Promise<Array<capture.AdapterStatusInfo>>;

export function RebuildFilterPipeline():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
